import os

BARBEROUSSE_STANDALONE = os.getenv("BARBEROUSSE_STANDALONE", False)
BARBEROUSSE_WORKER_CONFIG_FILE = os.getenv("BARBEROUSSE_WORKER_CONFIG_FILE")

BARBEROUSSE_WORKER_CONFIG_ETCD = {key.replace("BARBEROUSSE_WORKER_ETCD_", "").lower(): value for key, value in
                                  os.environ.items() if key.startswith("BARBEROUSSE_WORKER_ETCD_")}

BARBEROUSSE_PERSITENCE_CONFIG_FILE = os.getenv("BARBEROUSSE_PERSITENCE_CONFIG_FILE")
BARBEROUSSE_PERSITENCE_CONFIG_ETCD = os.getenv("BARBEROUSSE_PERSITENCE_CONFIG_ETCD")

BARBEROUSSE_GATEWAY_CONFIG_FILE = os.getenv("BARBEROUSSE_GATEWAY_CONFIG_FILE")
BARBEROUSSE_GATEWAY_CONFIG_ETCD = os.getenv("BARBEROUSSE_GATEWAY_CONFIG_ETCD")
