import os

BARBEROUSSE_STANDALONE = os.getenv("BARBEROUSSE_STANDALONE", 0)
BARBEROUSSE_DEBUG = os.getenv("BARBEROUSSE_DEBUG", 0)
BARBEROUSSE_WORKER_CONFIG_FILE = os.getenv("BARBEROUSSE_WORKER_CONFIG_FILE")
