version: '2'
services:
    broker:
        hostname: broker
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=barberousse
            - RABBITMQ_DEFAULT_PASS=barberousse
        ports:
            - "5672:5672"

    worker:
        build:
            context: .
            dockerfile: dockerfiles/worker/Dockerfile
        volumes:
            - .:/app
        links:
            - broker
            - database
        depends_on:
            - broker
            - database
        environment:
          - BARBEROUSSE_WORKER_CONNECTION_HOST=broker
          - BARBEROUSSE_DATABASE_CONNECTION_HOST=database
    gateway:
        build:
            context: .
            dockerfile: dockerfiles/gateway/Dockerfile
        volumes:
            - .:/app
        links:
            - broker
            - database
            - worker
        depends_on:
            - broker
            - database
            - worker
        environment:
          - BARBEROUSSE_WORKER_CONNECTION_HOST=broker
          - BARBEROUSSE_DATABASE_CONNECTION_HOST=database
        ports:
            - "8000:8000"
    database:
        hostname: database
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
          - MONGO_INITDB_ROOT_USERNAME=barberousse
          - MONGO_INITDB_ROOT_PASSWORD=barberousse
        volumes:
          - mongodb:/tmp/db

volumes:
  mongodb: